### ISSUE TITLE
Q: base conversion small difference?

### ISSUE THREAD

**Issue by Xotic750** [MikeMcl/bignumber.js#136]
Just wondered what causes the small difference with the following:

```
console.log(new BigNumber((1.1).toString(36), 36).toString());
// 1.1000000000000001094

console.log(new BigNumber((1.1).toString(2), 2).toString());
// 1.10000000000000008882
```

Is it caused by Javascript's base conversion or by the algorithm that BigNumber uses?

**Comment by MikeMcl** [comment]
It's caused by the JavaScript base conversion: `(1.1).toString(2)` returns the exact value, but the value returned by `(1.1).toString(36)` is rounded.

The exact underlying binary value of the JavaScript number `1.1` is in decimal

```js
exactValue = (1.1).toFixed(51)
'1.100000000000000088817841970012523233890533447265625'
```

The following two results match exactly.

```js
console.log((1.1).toString(2));
// '1.000110011001100110011001100110011001100110011001101'

BigNumber.set({DECIMAL_PLACES: 100});

console.log(new BigNumber(exactValue).toString(2));
// '1.000110011001100110011001100110011001100110011001101'
```

The next two don't match. The JavaScript version is rounded.

```js
console.log((1.1).toString(36));
'1.3llllllllm'

console.log(new BigNumber(exactValue).toString(36));
'1.3lllllllllxagau2ctidswz5mi' 
```

**Comment by Xotic750** [comment]
Thanks for that. ;)
