### ISSUE TITLE
In 6.0.0 toString with base 64 doesn't work out of the box anymore

### ISSUE THREAD

**Issue by Auswaschbar** [MikeMcl/bignumber.js#142]
Hi,

I guess this is because the of the ALPHABET changes of issue #137. In 5.0.0, toString called with a base 64 worked without additional configs. Now in 6.0.0 it gives an out of range error.

Working around this issue is easy enough as it is a simple configuration variable, but to improve the out-of-the-box experience I suggest using base64 as a default alphabet.

Thanks a lot for your efford

**Comment by MikeMcl** [comment]
I decided to go back to 36 because that matches the limit of `Number.prototype.toString`, and because there is no standard base 64 alphabet, in particular, there are no standard characters for character 63 and 64, and because I doubt the higher bases are used enough to justify their inclusion by default.

```js
BigNumber.set({
  ALPHABET: '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ$_'
});
```

The good thing now is that maximum base can be as large as the user wants it to be.

Thanks for the feedback .
