### ISSUE TITLE
Full integers from floats

### ISSUE THREAD

**Issue by shaunlebron** [MikeMcl/bignumber.js#162]
The new [BigInts](https://github.com/tc39/proposal-bigint) in JS read full integers out of a float, even those outside the [safe range](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isSafeInteger).  You can run the following in Chrome Canary to see this:

```
> BigInt(2**1023)

8988465674311579538646525953945123668089884894711532863671504057886633790275048
1566354238661203768010560056939935696678829394884407208311246423715319737062188
8839467124327426381511098006230470597265414760425028844190753411712314407369565
55270413618581675255342293149119973622969239858152417678164812112068608n
```

So, `2**1023` is outside the _safe_ integer range, but BigInt still reads it out at full precision ([tc39 had a discussion on why here](https://github.com/tc39/proposal-bigint/issues/132))

Ideally, BigNumber.js could do this as well, so I wrote a function to spit out all the digits below:

https://beta.observablehq.com/@shaunlebron/huge-floating-integers#renderFullInt

**Comment by MikeMcl** [comment]
I enjoyed your article, and your algorithm may be useful if I decide to add a method or option for a Number's underlying binary value to be used when constructing a BigNumber.

```javascript
x = BigNumber.fromDouble(0.1)
x.toString()    // '0.1000000000000000055511151231257827021181583404541015625'
```

I do not want that as the default behaviour for the BigNumber constructor though, as I think it is simpler and more intuitive to use a Number's decimal `toString` value rather than its 'true' binary value.

```javascript
x = new BigNumber(2)
x.plus(0.1).toString()    // '2.1'
```

See also, [Loses digits at Decimal construction time](https://github.com/MikeMcl/decimal.js/issues/61), a related issue regarding *decimal.js*.

Thanks for your input and the interesting links.

**Comment by shaunlebron** [comment]
Neat!  sounds like a good direction 👍
