### ISSUE TITLE
decimalPlaces don't work as expected

### ISSUE THREAD

**Issue by mkuzmik** [MikeMcl/bignumber.js#173]
```
const x = new BigNumber('123.123456');
const to2Decimal = x.decimalPlaces(2);
console.log(typeof to2Decimal);
console.log(to2Decimal);

Expected result:
> object
> BigNumber....

Actual result:
> number
> 6
```

**Comment by MikeMcl** [comment]
Previous to *v6.0.0* the `decimalPlaces` method returns the number of decimal places of the BigNumber it is called upon. From *v6.0.0*, if an argument is passed to the method, it returns a new BigNumber with the specified number of decimal places, i.e. the method is now *get/set* instead of just *get*.

Conclusion: you are reading the current documentation, but using an earlier version of this library.
