### ISSUE TITLE
Compatibility between v5 and v7

### ISSUE THREAD

**Issue by justinkchen** [MikeMcl/bignumber.js#202]
This is mostly due to my limited understanding of npm, but if I make an API package that uses BigNumber 7 as a dependency, if someone wants to use my API with BigNumber v5, would the BigNumber objects that they pass in cause issues when being used in the node_module code?

**Comment by josdejong** [comment]
https://medium.com/learnwithrahul/understanding-npm-dependency-resolution-84a24180901b

**Comment by justinkchen** [comment]
Thank you for that, but that isn't exactly what I'm asking. What I'm wondering is if someone creates an app using BigNumber v5, and creates a new BigNumber object...if they pass that object down to my API package that uses BigNumber v7 internally, would it be able to use the BigNumber object with no problem?

**Comment by josdejong** [comment]
Well, then you're mixing two incompatible versions of BigNumber in the same app together. If you keep track on which BigNumber version you're using and reckon with the API differences it can work in theory, but in practice it will be really hard since you will be mixing instances of the the two versions together. It's probably safest to introduce a wrapper API around the library using the differing version of BigNumber, so you're dealing with just one version in the app. Alternatively, well, it may just work, and if you add enough unit testing you may be confident enough that it all works fine.

**Comment by justinkchen** [comment]
Okay yea thats what I was kind of thinking would happen which is why I was hesitant to upgrade. Thanks for that insight! I will see what is the best way to move forward. Thanks for the fast responses!

**Comment by justinkchen** [comment]
Oh nice good to know!
