### ISSUE TITLE
toString(64) concept

### ISSUE THREAD

**Issue by Igorpollo** [MikeMcl/bignumber.js#236]
I'm trying to reproduce `toString(64)` in another language.
But I cant undestand It.
Can you tell me the concept or method used to archive it?

**Comment by MikeMcl** [comment]
Well, converting an integer to another base is straightforward. If a number is not an integer, the method I use is to convert the number as if it is an integer then divide the result by its base raised to a power such that the fraction part is restored.

For example, to convert the number 1234567890.123456789, we convert the integer 1234567890123456789 to base 64, then divide the result by the number 10**9 converted to base 64. 
In the same way, if we were converting the number 456.78, we would convert 45678 to base 64, then divide it by 10**2 converted to base 64.

The tricky part is to implement the division operation, as you will need to divide two base 64 values.

In this library, a base 64 value would be stored as an array, for example [45, 63, 16, 34, 2] with each element a value from 0-63, and the division operation here works irrespective of the base or number of digits of the inputs.

The result of the division operation will be another array of base 64 numbers, which then simply needs to be mapped to the characters in the base 64 alphabet you choose.

The above may not be perfectly accurate, as it has been a while since I have thought about this, but that is the general idea.

**Comment by Igorpollo** [comment]
Thanks for response. Ill close the issue!
