### ISSUE TITLE
[Support] Using BigNumber.js for blockchain app

### ISSUE THREAD

**Issue by quangnv13** [MikeMcl/bignumber.js#314]
Hello everyone, now i'm using BigNumber.js for frontend of my blockchain app. It's work perfectly but some use case with uint256 value: `603563865116404668245589250390106310780736245694817307641463070622848318552` and use code bellow:
`new BigNumber(603563865116404668245589250390106310780736245694817307641463070622848318552).toString(10)`
return value is `603563865116404600000000000000000000000000000000000000000000000000000000000`. I need input number with big value and return origin value as string.

Someone can help me solution for this?

**Comment by shuckster** [comment]
That number is being invisibly transformed by the JavaScript runtime to the output you are seeing because it is above Number.MAX_SAFE_INTEGER.

Your inputs to BigNumber should be strings only.

Try to avoid using the native number-type completely, because it has [more problems](https://stackoverflow.com/questions/588004/is-floating-point-math-broken) than just this one.

**Comment by quangnv13** [comment]
> That number is being invisibly transformed by the JavaScript runtime to the output you are seeing because it is above Number.MAX_SAFE_INTEGER.
> 
> Your inputs to BigNumber should be strings only.
> 
> Try to avoid using the native number-type completely, because it has [more problems](https://stackoverflow.com/questions/588004/is-floating-point-math-broken) than just this one.

Thanks for reply

**Comment by MikeMcl** [comment]
Yes, and unless you want the value rounded to the current `DECIMAL_PLACES` and `ROUNDING_MODE` settings, use the more efficient `toString()` rather than `toString(10)`.
