### ISSUE TITLE
Issue toNumber() function round up when number is too big (v9.1.1)

### ISSUE THREAD

**Issue by Sotatek-ThangNguyen2** [MikeMcl/bignumber.js#346]
I have a issue with toNumber() function.
I try with BigNumber version:
"bignumber.js": "9.1.1",

https://codesandbox.io/s/bignumber-js-forked-sewfsh?file=/src/index.js:0-780

999999999999998400000000000000000000 - 30000000000000000000

Expect Result:  999999999999998370000000000000000000
With toNumber(), same it Rounding Up result: 
9.999999999999984e+35
(from 37 -> 40)

<img width="1835" alt="screenshot" src="https://user-images.githubusercontent.com/61672403/234557478-4f8aad10-7835-42a7-83ad-dd16280d0a81.png">

**Comment by shuckster** [comment]
This is normal. Your number is way beyond `Number.MAX_SAFE_INTEGER`.

Use `toString` instead of `toNumber`.

Incidentally, JavaScript numbers also exhibit [binary floating-point rounding artefacts](https://0.30000000000000004.com/), which is why we need libraries like `bignumber.js` in the first place.

**Comment by Sotatek-ThangNguyen2** [comment]
@shuckster thanks
