### ISSUE TITLE
Provide method for moving the decimal point

### ISSUE THREAD

**Issue by clark800** [MikeMcl/bignumber.js#49]
The docs say that BigNumber.e should be considered read-only, and my testing confirms that setting it is not reliable. It seems that given the internal representation, it should be easy to add a "shift" method that moves the decimal point. This would be equivalent to multiplying/dividing by powers of 10, but much more efficient and not requiring setting DECIMAL_PLACES to much larger numbers (if you have a large number and multiply by 10^(-50), the second term can get truncated to 0, making the result 0).

This would be very useful for the obvious application of multiplying by powers of 10, but also for situations where you need to convert to a different BigNumber representation and you need to extract the first N digits of the mantissa.

**Comment by MikeMcl** [comment]
Yes, previous to v2.0.0 it was fine to write to the `e` property of a BigNumber, but unfortunately that is no longer the case.

I agree that a `shift` method would be a straightforward addition and that it would simply and potentially optimise multiplying/dividing by powers of 10, but as the result of a multiplication is not affected by the `DECIMAL_PLACES` setting it would basically just be providing syntactic sugar for `times`.

    n.shift(-9).equals(n.times(1e-9))    // true

Also, I would probably implement it internally by using `times` anyway, because that would be easiest and it would not be significantly less efficient then doing it any other way. 

It is also possible to extract N digits of the mantissa currently, using `toPrecision`.

Thanks for the suggestion. I think on balance it would be a worthwhile addition.

**Comment by MikeMcl** [comment]
Added a `shift` method in v2.0.1.
