### ISSUE TITLE
Feature Request: Binary Bitshift operator

### ISSUE THREAD

**Issue by Arlen22** [MikeMcl/bignumber.js#70]
One thing that would be really nice would be a bitshift operation. One that could go either direction using only bitshift and bitwise operators, no arithmatic, if possible. For doubling and halfing values the speed should be a lot faster than times or divide, I'm guessing. Times is already faster than divide, but this would probably be even faster.

**Comment by MikeMcl** [comment]
There is already a [shift](http://mikemcl.github.io/bignumber.js/#shift) method, but it just uses `times` under the hood. (I notice that the `shift` method is currently missing from the API image in the README.)

The value of a Bignumber is not stored internally in a binary or power of two form so it is not really feasible to use bitwise operations.

**Comment by Arlen22** [comment]
When I open Google Chrome's console and type in `new BigNumber('7854923758493275894032758940327589403278590437285428832')`, and then inspect the result, the coefficient array appears to be an array of integers. 

I did, however, try it, and it appears that the integers are bigger than what the bit shift operator can handle. They would probably have to be modified.

**Comment by MikeMcl** [comment]
I'm not clear if we are talking about the internal optimisation of the library or about adding bitwise methods to the API.

Regarding the latter, most decimal values with digits after the decimal point cannot be represented in binary, so that's a non-starter. 

As for the internal optimisation for the library, there would almost cetainly be no performance improvement at all in replacing for example `*` with `<<` for power of two multiplications. Bitwise operations may actually be slower if a JS number first needs to be first converted to a 32 bit integer. And regardless, the speed of native arithmetic is not a significant factor in the performance of the library.

**Comment by Arlen22** [comment]
The code I am trying to optimize is `c = a.plus(b).times(0.5).floor();`, which is part of a Binary Search Division operation to return p mod m. Now, I may well be picking at tiny problems, and this may not be the most efficient division operation. A long division implementation I made is actually faster.

    var p = new BigNumber(divisor), m = new BigNumber(dividend), a = new BigNumber(0), b = p;
    var c,d;  // c will contain the quotient
    while(true){

        c = a.plus(b).times(0.5).floor(); //avg 7,000 nanoseconds
        d = m.times(c); //avg 2,500 ns

        if(d.lt(pm1)) a = c;
        else if (d.gt(p)) b = c;
        else return p.minus(d); //return p mod m
    }

**Comment by MikeMcl** [comment]
At first glance I don't see any obvious optimisations to be made and I don't have time to analyse further.

Good luck.
