### ISSUE TITLE
round confused

### ISSUE THREAD

**Issue by LiJohnson** [MikeMcl/bignumber.js#82]
```js
new BigNumber(180).times( new BigNumber(0.08).div(360) ).times(10).round(2,3).toNumber()
```
I think this code output should be ```0.4```,but is ```0.39``` in fact.

**Comment by MikeMcl** [comment]
Well,  `1800 x 0.00022222222222222222 = 0.399999999999999996` which is `0.39` when rounded to two decimal places using rounding mode `3`, i.e. `ROUND_FLOOR`.

**Comment by LiJohnson** [comment]
why ```0.00022222222222222222```?
![image](https://cloud.githubusercontent.com/assets/2616788/11581084/2269e1d8-9a79-11e5-81f2-de2dd00ea60f.png)

**Comment by MikeMcl** [comment]
If you are getting `00022222222222222223` it means you have set the division rounding mode to `0`, i.e. `ROUND_FLOOR`, or 2, i.e. `ROUND_CEIL`. 
Because of the limits of the precision of JavaScript numbers

    console.log(0.00022222222222222222);    // 0.00022222222222222223

so to check the result, use `toString()` or `valueOf`, not `toNumber()`.

    new BigNumber(0.08).div(360).toString();    // 0.00022222222222222222

If you are still getting `00022222222222222223` it means you have set the division rounding mode to `0`, i.e. `ROUND_FLOOR`, or 2, i.e. `ROUND_CEIL`. 

    BigNumber.config({ ROUNDING_MODE: 0 });
    BigNumber.config({ ROUNDING_MODE: BigNumber.ROUND_FLOOR });

By default the rounding mode is `4`, i.e. `ROUND_HALF_UP`, in which case the result of the division is `00022222222222222222`.

**Comment by LiJohnson** [comment]
:+1:
