### ISSUE TITLE
Suggestion: Changelogs in new releases

### ISSUE THREAD

**Issue by sbrl** [MikeMcl/bignumber.js#85]
A quick changelog containing interesting changes would be nice - it lets people know what's changed between releases.

**Comment by MikeMcl** [comment]
There is already a Change Log at the bottom of the README.
Or do you mean I should include some notes on the Releases page? 
Or make the Chnage Log a separate file?

**Comment by sbrl** [comment]
Sorry, I wasn't clear - I meant notes on the release page. I didn't see them at the bottom of the readme!

**Comment by MikeMcl** [comment]
I agree that it would be good to have the change log notes on the Releases page.
As it may be a month or so before I can get round to doing this (because I am trying to get the next release of decimal.js out by the new year) I have added you as a collaborator so you can do it yourself if you choose to.

**Comment by sbrl** [comment]
I've updated your releases with information from the readme :)

**Comment by MikeMcl** [comment]
That's great, thanks.
